'use strict';

// Feature: exemptions-duty-matrix-grid, Property 14: Guard cells are never persisted
//
// Validates: Requirements 6.3
//
// Property 14 (design.md): For any matrix model, no guard Status_Cell produces
// an entry in any of the three store maps after `reduceMatrixToStore`.
//
// Guard is the implicit default Proctor_Status and is represented in the store
// by ABSENCE. Reducing a matrix model to the store therefore writes only
// exempt/duty/reserve cells; every guard cell (and any unrecognized in-memory
// value, which is treated as guard) must leave no trace of its own.
//
// This is a standalone Node test script. It exits non-zero on any failure.
//
//   node tests/ed-matrix-property-14-guard-never-persisted.test.js
//
// Precise, collision-safe formulation
// ------------------------------------
// The store keys are NOT one-per-cell. In particular the exempt bucket key is
// `['session', day, period, session]` (NO date), so two different-date sessions
// that share the same (day, period, session) write to the SAME exempt bucket.
// Counting one entry per cell therefore over-counts. The faithful statement of
// "guard cells are never persisted" is:
//
//   the SET of (map, bucket, proctorKey) entries actually persisted equals
//   exactly the SET generated by the NON-guard cells.
//
// If a guard cell ever contributed an entry, the actual set would contain a
// triple the non-guard cells never generate, and the sets would differ. This
// also covers the fully-guard model (expected set empty => store must be empty)
// and is robust to the exempt-bucket key collision above.
//
// Strategy:
//   - Build real Session_Columns via `buildSessionColumns` so every column's
//     sessionKey / exemptKey / subjects match the keys `reduceMatrixToStore`
//     writes.
//   - Build Proctor_Rows whose cells are random STATUS values, biased to
//     include MANY guard cells and a share of unrecognized values (treated as
//     guard and so also non-persisting).
//   - Proctor keys are distinct by construction (unique cin / som / idx
//     fallback).
//   - Reduce, then assert the actual persisted triple-set equals the triple-set
//     the non-guard cells generate.
//   - Plus an explicit fully-guard model => three empty maps.

const assert = require('assert');
const fc = require('fast-check');

const M = require('../js/exams/ed-matrix-logic.js');
const { reduceMatrixToStore, buildSessionColumns, getProctorExemptionKey, STATUS } = M;

const MIN_CASES = 100;

// The three persisted (non-guard) statuses.
const NON_GUARD = [STATUS.EXEMPT, STATUS.DUTY, STATUS.RESERVE];

// Values that are NOT one of exempt/duty/reserve. Each must be treated as guard
// and therefore produce NO store entry. Includes STATUS.GUARD plus a spread of
// unrecognized junk.
const GUARD_LIKE = [STATUS.GUARD, '', 'no', 'unknown', 'GUARD', 'Exempt', 'حراسة', null, undefined, 0, false];

// A single cell status: weighted toward guard-like values (the property's
// focus) with a healthy share of real non-guard statuses.
const cellStatusArb = fc.oneof(
    { weight: 6, arbitrary: fc.constantFrom(...GUARD_LIKE) },
    { weight: 4, arbitrary: fc.constantFrom(...NON_GUARD) }
);

// A schedule entry (drives a Session_Column). Subjects vary so columns end up
// single- and multi-subject (a duty/reserve cell writes one entry per subject).
const scheduleEntryArb = fc.record({
    date_year: fc.constant(2025),
    date_month: fc.integer({ min: 1, max: 12 }),
    date_day: fc.integer({ min: 1, max: 28 }),
    day: fc.constantFrom('الأول', 'الثاني', 'الثالث'),
    period: fc.constantFrom('صباحا', 'زوالا'),
    session: fc.constantFrom('الحصة الأولى', 'الحصة الثانية', 'الحصة الثالثة'),
    subject_name: fc.constantFrom('الرياضيات', 'العربية', 'الفيزياء', 'التاريخ', ''),
    order: fc.integer({ min: 1, max: 50 })
});

// Unique proctor ids -> proctor records with GUARANTEED-distinct keys:
//   kind 0 -> cin = 'cin<id>'   (key = 'cin<id>')
//   kind 1 -> som = 'som<id>'   (key = 'som<id>', cin empty)
//   kind 2 -> both empty        (key = 'idx_<index>', unique by index)
const proctorsArb = fc.uniqueArray(fc.integer({ min: 1, max: 99999 }), { minLength: 1, maxLength: 6 })
    .map((ids) => ids.map((id) => {
        const kind = id % 3;
        if (kind === 0) {
            return { cin: 'cin' + id, som: '' };
        }
        if (kind === 1) {
            return { cin: '', som: 'som' + id };
        }
        return { cin: '', som: '' };
    }));

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------

const SEP = '\u0000'; // NUL separator: cannot appear in any key.

// The dated `sessionKey|subject` bucket keys reduceMatrixToStore writes for a
// duty/reserve cell of this column (subject-less session uses a trailing '').
function dutyReserveBucketKeys(col) {
    const subjects = Array.isArray(col.subjects) ? col.subjects : [];
    const list = subjects.length ? subjects : [''];
    return list.map((subj) => col.sessionKey + '|' + (subj || ''));
}

// Build a MatrixModel from generated proctors, schedule entries, and a cell
// status grid. cellGrid[rowIdx] is an array of statuses indexed (mod length)
// per session column.
function buildModel(proctors, scheduleEntries, cellGrid) {
    const sessions = buildSessionColumns(scheduleEntries);
    const rows = proctors.map((proc, idx) => {
        const cells = new Map();
        const grid = cellGrid[idx % cellGrid.length] || [STATUS.GUARD];
        sessions.forEach((col, s) => {
            cells.set(col.sessionKey, grid[s % grid.length]);
        });
        return {
            proctorKey: getProctorExemptionKey(proc, idx),
            cells: cells
        };
    });
    return { sessions: sessions, rows: rows, totalSessions: sessions.length };
}

// The SET of persisted triples that the NON-guard cells of the model dictate.
// Guard / unrecognized cells contribute nothing.
function expectedTriples(model) {
    const set = new Set();
    for (const row of model.rows) {
        const key = row.proctorKey;
        for (const col of model.sessions) {
            const status = row.cells.get(col.sessionKey);
            if (status === STATUS.EXEMPT) {
                set.add('E' + SEP + col.exemptKey + SEP + key);
            } else if (status === STATUS.DUTY) {
                dutyReserveBucketKeys(col).forEach((b) => set.add('D' + SEP + b + SEP + key));
            } else if (status === STATUS.RESERVE) {
                dutyReserveBucketKeys(col).forEach((b) => set.add('R' + SEP + b + SEP + key));
            }
            // guard / unrecognized => nothing.
        }
    }
    return set;
}

// The SET of triples ACTUALLY present in a reduced store.
function actualTriples(store) {
    const set = new Set();
    const add = (tag, map) => {
        if (!map) {
            return;
        }
        for (const bucket of Object.keys(map)) {
            const inner = map[bucket];
            if (inner && typeof inner === 'object') {
                for (const key of Object.keys(inner)) {
                    set.add(tag + SEP + bucket + SEP + key);
                }
            }
        }
    };
    add('E', store.exemptionsData);
    add('D', store.dutyData);
    add('R', store.reservesData);
    return set;
}

function sortedArr(set) {
    return Array.from(set).sort();
}

let runCount = 0;

// ---------------------------------------------------------------------------
// Property 14.
// ---------------------------------------------------------------------------

console.log('[test] exemptions-duty-matrix-grid — Property 14: guard cells are never persisted');

try {
    fc.assert(
        fc.property(
            proctorsArb,
            fc.array(scheduleEntryArb, { minLength: 1, maxLength: 6 }),
            fc.array(fc.array(cellStatusArb, { minLength: 1, maxLength: 6 }), { minLength: 1, maxLength: 6 }),
            (proctors, scheduleEntries, cellGrid) => {
                runCount++;
                const model = buildModel(proctors, scheduleEntries, cellGrid);
                const store = reduceMatrixToStore(model);

                const expected = expectedTriples(model);
                const actual = actualTriples(store);

                // The store contains exactly what the NON-guard cells dictate —
                // no guard cell added anything (otherwise `actual` would contain
                // a triple not in `expected`).
                assert.deepStrictEqual(
                    sortedArr(actual),
                    sortedArr(expected),
                    'persisted store does not equal the set generated by non-guard cells; ' +
                    'a guard cell was persisted (or a non-guard cell was dropped)'
                );
            }
        ),
        { numRuns: MIN_CASES, verbose: true }
    );

    // Explicit edge case: a fully-guard model yields three empty maps.
    (function fullyGuard() {
        const scheduleEntries = [
            { date_year: 2025, date_month: 6, date_day: 10, day: 'الأول', period: 'صباحا', session: 'الحصة الأولى', subject_name: 'الرياضيات', order: 1 },
            { date_year: 2025, date_month: 6, date_day: 11, day: 'الثاني', period: 'زوالا', session: 'الحصة الثانية', subject_name: 'العربية', order: 2 }
        ];
        const proctors = [{ cin: 'A1', som: '' }, { cin: '', som: 'S2' }, { cin: '', som: '' }];
        const sessions = buildSessionColumns(scheduleEntries);
        const rows = proctors.map((proc, idx) => {
            const cells = new Map();
            sessions.forEach((col) => cells.set(col.sessionKey, STATUS.GUARD));
            return { proctorKey: getProctorExemptionKey(proc, idx), cells: cells };
        });
        const model = { sessions: sessions, rows: rows, totalSessions: sessions.length };

        const store = reduceMatrixToStore(model);
        assert.deepStrictEqual(store.exemptionsData, {}, 'fully-guard model must yield empty exemptionsData');
        assert.deepStrictEqual(store.dutyData, {}, 'fully-guard model must yield empty dutyData');
        assert.deepStrictEqual(store.reservesData, {}, 'fully-guard model must yield empty reservesData');
        runCount++;
    })();

    console.log('PASS ed-matrix Property 14: Guard cells are never persisted (' + runCount + ' cases incl. fully-guard edge case)');
    process.exit(0);
} catch (err) {
    console.error('FAIL: Property 14 violated');
    console.error(err && err.message ? err.message : err);
    process.exit(1);
}
