/**
 * Regression test — display helpers never count synthetic rooms (Task 3.6)
 *
 * Validates: Requirement 3.6
 *
 *   "WHEN getSummaryCandidateCountForLevel وبقية الدوال التي تقرأ
 *    examCenterRoomsData لأغراض العرض (غير توزيع المراقبين) تُستدعى
 *    THEN the system SHALL CONTINUE TO تُرجع نتائجها الحالية دون احتساب
 *    الصفوف الافتراضية، لأن هذه الصفوف مقصورة على مسار بناء مُدخَل v2."
 *
 * Why mirror the helper here?
 * --------------------------
 * `getSummaryCandidateCountForLevel` lives inside a <script> block in
 * `exams-proctors.html`; it closes over `window.api.examConfig` and the
 * page-local `year` variable, so it cannot be `require`d directly. All the
 * other Task 3.x tests follow the same mirroring pattern
 * (see tests/proctor-v2-render-synthetic-warnings.test.js,
 *  tests/proctor-v2-synthetic-room-helpers.test.js, ...).
 *
 * If the production helper in `exams-proctors.html` changes, this mirror MUST
 * be updated to match.
 *
 * Production reference (exams-proctors.html §6171):
 *
 *   async function getSummaryCandidateCountForLevel(levelName) {
 *       const roomsData =
 *           (await window.api.examConfig.get(year, 'examCenterRoomsData')) || {};
 *       let total = 0;
 *       for (const [key, value] of Object.entries(roomsData)) {
 *           if (!key.startsWith(levelName + '__')) continue;
 *           total += parseInt(value.count) || 0;
 *       }
 *       return total;
 *   }
 *
 * The point of this test is to lock in the contract:
 *   - display count reads `examCenterRoomsData` ONLY (never `roomsList`
 *     produced by `buildV2Input`)
 *   - synthetic rows generated by the v2 input builder live only in the
 *     algorithm's `roomsList` and never leak into user-visible counts
 *   - `examCenterLevels[L].rooms` (the "expected" count) does NOT contribute
 *     to the display count — so a level with `rooms=2` and `M=0` shows `0`,
 *     not `2`, after the fix
 */

'use strict';

const assert = require('assert');

// ----------------------------------------------------------------------------
// Helper mirror — byte-for-byte equivalent of the production implementation.
// ----------------------------------------------------------------------------
function mirrorGetSummaryCandidateCountForLevel(levelName, roomsData) {
    const data = roomsData || {};
    let total = 0;
    for (const [key, value] of Object.entries(data)) {
        if (!key.startsWith(levelName + '__')) continue;
        total += parseInt(value && value.count) || 0;
    }
    return total;
}

// ----------------------------------------------------------------------------
// Test harness
// ----------------------------------------------------------------------------
const tests = [];
function test(name, fn) { tests.push({ name: name, fn: fn }); }

function runAll() {
    let passed = 0;
    let failed = 0;
    const failures = [];
    for (const t of tests) {
        try {
            t.fn();
            console.log('  [pass] ' + t.name);
            passed++;
        } catch (e) {
            console.log('  [FAIL] ' + t.name + ': ' + e.message);
            failed++;
            failures.push({ name: t.name, message: e.message });
        }
    }
    console.log('\n[test] display-functions regression: ' + passed + ' passed, ' + failed + ' failed');
    if (failed > 0) {
        console.log('\n=== FAILURES ===');
        console.log(JSON.stringify(failures, null, 2));
        process.exit(1);
    }
}

console.log('[test] display helpers never count synthetic rooms (Task 3.6)');

// ----------------------------------------------------------------------------
// Primary requirement: rooms=2 in examCenterLevels but M=0 in roomsData → 0.
// This is the exact assertion named in tasks.md §3.6.
// ----------------------------------------------------------------------------
console.log('\n  --- primary regression: synthetic rows never leak into display count ---');

test('level with expected rooms=2 but NO stored rows (M=0) → candidate count is 0 (not 2)', function () {
    // examCenterRoomsData is empty for the level. `examCenterLevels[L].rooms`
    // is a display-orthogonal reference: it MUST NOT influence this count.
    const roomsData = {};
    const got = mirrorGetSummaryCandidateCountForLevel('L1', roomsData);
    assert.strictEqual(got, 0,
        'display count must read examCenterRoomsData only; expected 0 got ' + got);
});

test('level with expected rooms=2 and M=0 — even if buildV2Input later added synthetic rows, they stay out of roomsData', function () {
    // This mirrors the real runtime: `buildV2Input` produces synthetic rows
    // in-memory inside `roomsList` but never writes them back to
    // `examCenterRoomsData`. The display helper reads roomsData only, so it
    // keeps returning 0.
    const roomsData = {}; // roomsData is the ONLY source the helper sees
    const got = mirrorGetSummaryCandidateCountForLevel('L1', roomsData);
    assert.strictEqual(got, 0);
});

// ----------------------------------------------------------------------------
// Preservation: real rows still aggregate as before.
// ----------------------------------------------------------------------------
console.log('\n  --- preservation: real rows still aggregate correctly ---');

test('two saved rows with count=25 each → total=50', function () {
    const roomsData = {
        'L1__1': { count: 25, roomName: 'A' },
        'L1__2': { count: 25, roomName: 'B' }
    };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', roomsData), 50);
});

test('mixed numeric / string count values are coerced via parseInt', function () {
    const roomsData = {
        'L1__1': { count: '25' },          // parseInt → 25
        'L1__2': { count: 10 },             // → 10
        'L1__3': { count: '30 students' }, // parseInt → 30
        'L1__4': { count: '' }              // parseInt → NaN → 0
    };
    // 25 + 10 + 30 + 0 = 65
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', roomsData), 65);
});

test('rows for other levels are ignored', function () {
    const roomsData = {
        'L1__1': { count: 20 },
        'L2__1': { count: 30 },
        'L2__2': { count: 25 }
    };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', roomsData), 20);
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L2', roomsData), 55);
});

test('rooms with missing or non-numeric count default to 0', function () {
    const roomsData = {
        'L1__1': { /* no count */ roomName: 'A' },
        'L1__2': { count: null },
        'L1__3': { count: undefined },
        'L1__4': { count: 42 }
    };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', roomsData), 42);
});

// ----------------------------------------------------------------------------
// Edge cases.
// ----------------------------------------------------------------------------
console.log('\n  --- edge cases ---');

test('unknown level returns 0 (not undefined, not NaN)', function () {
    const roomsData = { 'L1__1': { count: 20 } };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('DOES_NOT_EXIST', roomsData), 0);
});

test('null / undefined roomsData → 0', function () {
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', null), 0);
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', undefined), 0);
});

test('empty roomsData → 0 for any level', function () {
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', {}), 0);
});

test('Arabic level name round-trips correctly (real-world scenario)', function () {
    const lvl = 'الأولى باكالوريا العلوم الرياضية - رسميون';
    const roomsData = {};
    roomsData[lvl + '__1'] = { count: 32 };
    roomsData[lvl + '__2'] = { count: 28 };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel(lvl, roomsData), 60);
});

test('synthetic-like entry (key carries __synthetic suffix) is never present in roomsData under normal flow', function () {
    // Sanity check: production buildV2Input never writes `_synthetic: true`
    // rows back into `examCenterRoomsData`. But even if a caller passed such a
    // value by mistake, the count is read from `value.count` so a row with
    // count=0 (the buildSyntheticRoomRow default) contributes 0.
    // See exams-proctors.html §buildSyntheticRoomRow — count is hard-coded 0.
    const roomsData = {
        'L1__1': { count: 25, roomName: 'A' },
        // Hypothetical leaked synthetic row — proves defense-in-depth: even
        // if it slipped in, its count is 0 so it does not inflate the total.
        'L1__99__synthetic': { count: 0, roomName: 'قاعة افتراضية 99', _synthetic: true }
    };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', roomsData), 25,
        'synthetic-shaped rows carry count=0 and must not inflate the display total');
});

// ----------------------------------------------------------------------------
// Prefix boundary: keys starting with the level name + "__" are matched
// strictly; a level whose name is a prefix of another must not leak.
// ----------------------------------------------------------------------------
test('startsWith boundary — level name prefix must not leak across levels', function () {
    const roomsData = {
        'L1__1': { count: 10 },
        'L10__1': { count: 100 } // starts with 'L1' but NOT with 'L1__'
    };
    assert.strictEqual(mirrorGetSummaryCandidateCountForLevel('L1', roomsData), 10,
        'L10 rows must not be counted towards L1');
});

runAll();
