const { registerStudentsIpc } = require('./students');
const { registerGradesIpc } = require('./grades');
const { registerSettingsIpc } = require('./settings-ipc');
const { registerCatalogIpc } = require('./catalog');
const { registerStudentProfileIpc } = require('./student-profile');
const { registerAbsencesIpc } = require('./absences');
const { registerAuthIpc } = require('./auth');
const { registerSchoolOpsIpc } = require('./schoolOps');
const { registerStaffIpc } = require('./staff');
const { registerTeacherAbsencesIpc } = require('./teacher-absences');
const { registerDailyReportIpc } = require('./daily-report');
const { registerCompensationIpc } = require('./compensation');
const { registerSupportSessionsIpc } = require('./support-sessions');
const { registerSystemTagsIpc } = require('./system-tags');
const { registerStaffAttendanceIpc } = require('./staffAttendance');
const { registerExamsIpc } = require('./exams');
const { registerSystemIpc } = require('./system');
const { registerSystemPrintIpc } = require('./system-print');
const { registerSystemBackupIpc } = require('./system-backup');
const { registerLicensingIpc } = require('./licensing');
const { registerOwnerTelemetryIpc } = require('./ownerTelemetry');
const { registerUpdaterIpc } = require('./updater');
const { registerPageVisibilityIpc } = require('./pageVisibility');
const { registerNotificationsIpc } = require('./notifications');
const { registerReportsIpc } = require('./reports');
const { registerInstitutionIpc } = require('./institution');
const { registerSyncIpc } = require('./sync');
const { registerTimetableDataIpc } = require('./timetable-data');
const { registerExamConfigDataIpc } = require('./exam-config-data');
const { registerInspectorsIpc } = require('./inspectors');
const { registerAppAdminIpc } = require('./app-admin');
const { registerDiagnosticsIpc } = require('./diagnostics');
const { registerAppDefaultsIpc } = require('./appDefaults');
const { startOutboxCleanup } = require('../sync/capture');

function registerAllIpcHandlers(ipcMain) {
    registerAuthIpc(ipcMain);
    registerStudentsIpc(ipcMain);
    registerGradesIpc(ipcMain);
    registerSettingsIpc(ipcMain);
    registerCatalogIpc(ipcMain);
    registerStudentProfileIpc(ipcMain);
    registerAbsencesIpc(ipcMain);
    registerSchoolOpsIpc(ipcMain);
    registerStaffIpc(ipcMain);
    registerTeacherAbsencesIpc(ipcMain);
    registerDailyReportIpc(ipcMain);
    registerCompensationIpc(ipcMain);
    registerSupportSessionsIpc(ipcMain);
    registerSystemTagsIpc(ipcMain);
    registerStaffAttendanceIpc(ipcMain);
    registerExamsIpc(ipcMain);
    registerSystemIpc(ipcMain);
    registerSystemPrintIpc(ipcMain);
    registerSystemBackupIpc(ipcMain);
    registerLicensingIpc(ipcMain);
    registerOwnerTelemetryIpc(ipcMain);
    registerUpdaterIpc(ipcMain);
    registerPageVisibilityIpc(ipcMain);
    registerNotificationsIpc(ipcMain);
    registerReportsIpc(ipcMain);
    registerInstitutionIpc(ipcMain);
    registerSyncIpc(ipcMain);
    registerTimetableDataIpc(ipcMain);
    registerExamConfigDataIpc(ipcMain);
    registerInspectorsIpc(ipcMain);
    registerAppAdminIpc(ipcMain);
    registerDiagnosticsIpc(ipcMain);
    registerAppDefaultsIpc(ipcMain);
    startOutboxCleanup();
}

module.exports = { registerAllIpcHandlers };
