/**
 * All pages managed by the page visibility system.
 * This list must match PAGE_VISIBILITY_CATALOG in js/utils.js.
 * Used by ensurePageVisibilitySchema() to seed the page_visibility table.
 */
module.exports = [
    'index.html',
    'students-list.html',
    'students-register.html',
    'students-files.html',
    'students-movement.html',
    'teachers-list.html',
    'teachers-schedule.html',
    'teachers-absence.html',
    'teachers-performance.html',
    'staff-attendance.html',
    'staff-daily-report.html',
    'timetable.html',
    'timetable-redistribution.html',
    'timetable-students.html',
    'timetable-rooms.html',
    'timetable-teachers.html',
    'results-hub.html',
    'analytics.html',
    'grades-sheets.html',
    'studentzero.html',
    'student-support.html',
    'absence-weekly.html',
    'absence-students.html',
    'absence-correspondence.html',
    'absence-analytics.html',
    'exams-schedule.html',
    'exams-proctors.html',
    'exams-rooms.html',
    'exams-tests.html',
    'reports-certificates.html',
    'reports-forms.html',
    'reports-semester.html',
    'settings-school.html',
    'settings-imports.html',
    'settings-users.html',
    'settings-license.html',
    'settings-logs.html',
    'student-profile-prototype.html',
    'communication-center-prototype.html',
];
